### ISSUE TITLE
super assignment in functions?

### ISSUE THREAD

**Issue by RenRMT** [ALKSE/hsstools#1]
I noticed a number of new functions now use the super-assignment (<<-) operator to create objects. I wanted to check first if there's a good reason for using these before removing them, but I think we generally should stay away from using them in functions because of the side-effects they produce (e.g. hss_rename() function in its current form now produces its expected output, but it also creates a new object 'data_nw_names' in the global environment.

**Comment by ALKSE** [comment]
Resolved!
